image: clockwise/docker-phpunit-alpain:master

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          # install composer vendor scripts
          - composer install
          - vendor/bin/phpunit --version
          - touch database/database.sqlite
          # migrate
          - php artisan migrate --seed
          # run tests
          - vendor/bin/phpunit