on: [pull_request]
jobs:
  demo-ci-runner:
    runs-on: ubuntu-latest

    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306 
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:

      - name: Checkout app code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@verbose
        with:
          php-version: 7.4
          coverage: xdebug
        env:
          update: true

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create test database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'

      - name: Setup Database
        run: |
          php artisan migrate --no-interaction -vvv
          php artisan db:seed

      - name: Run Service Testsuite with Coverage
        run: vendor/bin/phpunit --testsuite="Services Tests" --coverage-clover=coverage-service.xml

      - name: Upload service coverage report
        run: bash <(curl -s https://codecov.io/bash) -F service -f coverage-service.xml
      
      # - name: Run Controller Testsuite with Coverage
      #   run: vendor/bin/phpunit --testsuite="Controllers Tests" --coverage-clover=coverage-controller.xml

      # - name: Upload controller coverage report
      #   run: bash <(curl -s https://codecov.io/bash) -F controller -f coverage-controller.xml

      # - name: Run Complete Testsuite with Coverage
      #   run: vendor/bin/phpunit --coverage-clover=coverage.xml

      # - name: Upload overall coverage report
      #   run: bash <(curl -s https://codecov.io/bash) -f coverage.xml